name: Release
run-name: "Release v${{ inputs.version }}"
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version

concurrency:
  group: workflow-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.result }}
    concurrency:
      group: ref-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Collate Changelog
        id: changelog
        uses: actions/github-script@v7
        with:
          # language=javascript
          script: |
            const prerelease = context.payload.inputs.version.includes("-");
            const prs = await github.rest.search.issuesAndPullRequests({
                q: prerelease
                    ? `repo:${context.payload.repository.full_name} is:open sort:created-asc -label:released -label:in-prerelease`
                    : `repo:${context.payload.repository.full_name} is:open sort:created-asc -label:released`  // FIXME
            });
            const sections = {};
            for (const pr of prs.data.items) {
                if (!pr.body.includes("# Changelog")) {
                    continue;
                }
                const changelog = pr.body.split("# Changelog")[1].trim();
                let section = null;
                for (const line of changelog.split("\n")) {
                    if (!line.trim()) {
                        continue;
                    }
                    if (line.startsWith("## ")) {
                        section = line.substring(3).trim();
                        if (sections[section] === undefined) {
                            sections[section] = [];
                        }
                        continue;
                    }
                    sections[section].push(line.trim());
                }
            }
            let changelog = "";
            if (sections[null]) {
                changelog += sections[null].join("\n");
            }
            for (const section in sections) {
                if (section === null || sections[section].length === 0) {
                    continue;
                }
                changelog += `\n\n# ${section}\n`;
                changelog += sections[section].join("\n");
            }
            for (const pr of prs.data.items) {
                await github.rest.issues.addLabels({
                    owner: context.payload.repository.owner.login,
                    repo: context.payload.repository.name,
                    issue_number: pr.number,
                    labels: [prerelease ? "in-prerelease" : "released"]
                });
                if (!prerelease && pr.labels.find(label => label.name === "in-prerelease") !== undefined) {
                    await github.rest.issues.removeLabel({
                        owner: context.payload.repository.owner.login,
                        repo: context.payload.repository.name,
                        issue_number: pr.number,
                        name: "in-prerelease"
                    });
                }
            }
            return changelog.trim();
          result-encoding: string
      - name: Setup Git
        # language=bash
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Pull Weblate Changes
        continue-on-error: true
        # language=bash
        run: |
          git pull https://hosted.weblate.org/git/minecraft-access/mod/
      - name: Update Changelog
        if: !contains(inputs.version, '-')
        env:
          CHANGELOG: ${{ steps.changelog.outputs.result }}
        # language=bash
        run: |
          changelog=${CHANGELOG//$'\n'/\\n}
          changelog=${changelog//# /### }
          sed "/<!-- INSERT CHANGELOG HERE -->/a\\\\n## Release v${{ inputs.version }} ($(date +%Y-%m))\n${changelog}" -i ./docs/changelog.md
          git add ./docs/changelog.md
          git commit -m $'Updated changelog for v${{ inputs.version }}\n\nCo-authored-by: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>'
      - name: Tag
        # language=bash
        run: |
          git tag "v${{ inputs.version }}" -m $'${{ steps.changelog.outputs.result }}\n\nReleased-by: @${{ github.actor }}' --cleanup=whitespace
      - name: Push Changes
        # language=bash
        run: |
          git push --follow-tags
  release:
    name: Release (${{ matrix.loader.name }})
    needs:
      - prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        loader:
          - name: Fabric
            slug: fabric
          - name: NeoForge
            slug: neoforge
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }}
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Build
        # language=bash
        run: ./gradlew clean :${{ matrix.loader.slug }}:build -x test
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          # FIXME
#          modrinth-id: ${{ vars.MODRINTH_ID }}
#          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
#          curseforge-id: ${{ vars.CURSEFORGE_ID }}
#          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-tag: v${{ inputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-name: Minecraft Access v${{ inputs.version }}
          files: ./${{ matrix.loader.slug }}/build/libs/*+${{ matrix.loader.slug }}.jar
          name: Minecraft Access v${{ inputs.version }} for ${{ matrix.loader.name }}
          version: ${{ inputs.version }}+${{ matrix.loader.slug }}
          changelog: ${{ needs.prepare.outputs.changelog }}
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: ./${{ matrix.loader.slug }}/build/libs/*+${{ matrix.loader.slug }}.jar
